# Generated by Django 4.0.2 on 2022-05-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_created_at_question_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
