# Generated by Django 4.0.2 on 2022-05-19 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 21, 10, 58, 79638, tzinfo=utc)),
        ),
    ]
